import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
        <Providers>
          <TopNav />
          <main className='container mx-auto'>
            {children}
          </main>
        </Providers>
        </Suspense>
      </body>
    </html>
  );
}
